# Generated by Django 5.1.1 on 2024-10-31 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_alter_user_id_follow_post_follow_post_fo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="post_fo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_following",
                to="network.post",
            ),
        ),
    ]
