# Generated by Django 5.1.1 on 2024-11-06 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_post", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
